import type { ErrorEntry } from './types.ts';

const D = '2026-10-02';

/** Codes named by the assignment first, in the order they were given; then other codes a requester meets. */
export const errors: ErrorEntry[] = [
  {
    code: 'invalid_input',
    where: 'quote',
    status: '422 at the quote; a blocker at the check',
    cause:
      'The body breaks a field rule: a wrong type or length, two of skill, steps and template at once, a field the action refuses (for example `onchain` on job.open, `parentJobId` anywhere but job.continue, `repoUrl` without `baseCommit`), or a chain not open to launches.',
    fix:
      'Read `detail` and `problems`; each names the field. Move a launch to launch.open, a continuation to job.continue, and keep one of skill, steps or template. Nothing was charged.',
    observed: `${D}: job.open with onchain "evm_project" returned the blocker "a launch is not covered by the job price; ask for launch.open instead".`,
    docs: 'paid',
    required: true,
  },
  {
    code: 'invalid_payment_shape',
    where: 'submit',
    status: '400',
    cause:
      'The payment payload in the PAYMENT-SIGNATURE header has a key the plane does not list, at any depth. An SDK that attaches `extensions` with content is the usual cause; `accepted` not equal to the challenge’s `accepts[0]` and a wrong `resource.url` fail the same way.',
    fix:
      'Build the payload from the challenge only: `x402Version`, optional `resource`, `accepted` copied from `accepts[0]`, `payload.signature`, `payload.permit2Authorization`. Drop `extensions`, or send it empty. `detail` names the offending field.',
    observed: 'Not reproduced: it needs a signed payment. Documented from the docs and the payload shape they publish.',
    docs: 'paid',
    required: true,
  },
  {
    code: 'missing_fact token_supply',
    where: 'check',
    status: 'a blocker at the check, 422 at the quote',
    cause:
      'The request mints a token but does not say its total supply, and the evaluator needs it to plan the mint. `missing_fact` also comes as a suggestion (not a blocker) for facts the builders may decide, such as `numbers` or `access`; it blocks only when `required` is true.',
    fix:
      'State the supply in the request text. On a project or hook launch the only supply that deploys is 1,000,000,000 with 18 decimals, minted once; say that, or switch to `custom_token` with `economics` for your own. Give the token name and symbol in the same sentence: they are required facts too.',
    observed: `${D}: a job.open with onchain and no token facts returned blocking missing_fact for token_name, token_symbol and token_supply. A workflow that stated the fixed supply listed token_supply as "fixed" and passed.`,
    docs: 'workflow-body',
    required: true,
  },
  {
    code: 'unplannable_steps',
    where: 'check',
    status: 'a blocker at the check, 422 at the quote',
    cause:
      'A step names `paths` although its skill declares its own write budget. On the check date that was true of `write-readme-and-docs`, `gas-and-size-report` and `deploy-script`.',
    fix:
      'Remove `paths` from those steps. Keep `paths` on skills that need them, such as `write-foundry-tests`, `implement-component` and `refine-project`. The docs table lists `paths` as required for the three skills above; the live check contradicts it, and the live check decides.',
    observed: `${D}: a chain with write-readme-and-docs and paths ["README.md", "docs"] returned "step 2 (write-readme-and-docs) declares its own budget, so the step may not also name paths".`,
    docs: 'job-body',
    required: true,
  },
  {
    code: 'protected_path',
    where: 'check',
    status: 'a blocker at the check, 422 at the quote',
    cause:
      'A step’s `paths` includes a path no task may modify. `foundry.toml`, `lib` and `lib/**` are protected: the worker’s toolchain and vendored libraries are not yours to change.',
    fix:
      'Take them out of `paths`. Dependencies come from the worker’s vendored libraries and are committed by the worker; compiler settings follow the network’s pinned toolchain. Ask for behaviour in the objective instead.',
    observed: `${D}: write-foundry-tests with paths ["test", "foundry.toml", "lib"] returned three protected_path blockers, one each for foundry.toml, lib and lib/**, naming the node write_foundry_tests.`,
    docs: 'job-body',
    required: true,
  },
  {
    code: 'recheck_failed',
    where: 'check',
    status: 'a blocker at the check, 422 at the quote',
    cause:
      'The workflow evaluator rebuilt the plan and the rebuilt plan did not pass its own recheck. Vague rules are the usual cause: the checker cannot tell what the request wants, such as whether it wants a user-facing site at all. Asking a read-only role (adversarial-review, the audit nodes) to produce something, such as a failing test, is another.',
    fix:
      'Say plainly what the contracts do, who can call what, and whether there is a site and what it shows. Let the review review: ask the implementation steps for tests; the reviewer reports findings and never edits source or tests.',
    observed: `${D}: a workflow whose request read "Make a token that is good and fair" and asked the adversarial review to "write a failing test" returned recheck_failed: "The checker is not sure the request wants a user-facing website or application interface, which the plan includes. Say whether it does."`,
    docs: 'workflow-body',
    required: true,
  },
  {
    code: 'needs_revision',
    where: 'check',
    status: 'a blocker at the check, 422 at the quote',
    cause:
      'The evaluator judged that the request must change before it can be planned: rules too vague to build to, or an instruction a role cannot carry out. It travels with `recheck_failed` and the same causes.',
    fix:
      'Rewrite the request with concrete rules and numbers, then check again. Each `facts` row with state `missing` and `required: true` is a sentence you have to add.',
    observed: `${D}: not returned by any probe; the same vague inputs produced recheck_failed. Listed from the assignment’s own notes.`,
    docs: 'workflow-body',
    required: true,
  },
  {
    code: 'invalid_plan',
    where: 'check',
    status: 'a blocker at the check, 422 at the quote',
    cause:
      'The original plan could not be rebuilt. The usual trigger is size: `request` + `context` + `draft.objective`, folded together, above about 7,000 characters. Each field is allowed up to 16,000 on its own, so the fold is the limit that bites.',
    fix:
      'Cut the request to what the builders must know and move decisions into short `context` lines. Keep the draft objective to one or two sentences. A 7,900-character objective passed as a plain job.open on the same day; the fold applies to workflows.',
    observed: `${D}: a workflow with a 5,200-character request and a 2,600-character context returned invalid_plan ("Correct the invalid original plan before rebuilding") plus an unresolved_decision about source publication.`,
    docs: 'workflow-body',
    required: true,
  },
  {
    code: 'objective_too_large',
    where: 'check',
    status: 'a blocker at the check, 422 at the quote',
    cause:
      'The folded objective the evaluator writes for the first job is above its limit. Same root as `invalid_plan`: too much text across request, context and draft objective.',
    fix: 'Shorten as for `invalid_plan`. Put long specifications in a repository the job starts from (`repoUrl` + `baseCommit`) or in a named input file, not in the request.',
    observed: `${D}: not returned by any probe; the oversized workflow returned invalid_plan. Listed from the assignment’s own notes.`,
    docs: 'workflow-body',
    required: true,
  },
  {
    code: 'payer_not_owner',
    where: 'submit',
    status: '403',
    cause: 'A job.continue is being paid from a wallet other than the one that paid for the project (`paidBy` on the parent job). Refused before anything moves.',
    fix:
      'Pay from the project’s wallet. To build on a project you did not pay for, open a new job with its repository as `repoUrl` and `baseCommit`, and its accepted files as `inputs`.',
    observed: 'Not reproduced: it needs a payment. The free check cannot know which wallet will pay.',
    docs: 'continue',
    required: true,
  },
  {
    code: 'request_key_conflict',
    where: 'quote',
    status: '409',
    cause: 'The `requestKey` was used before with a different `action` or `input`. A key names one exact quote.',
    fix: 'Generate a new UUID for a new body. Reuse a key only to retry the identical quote; that returns 200 with the same order.',
    observed: 'Not reproduced: quoting creates an order and needs a request token. Documented from the docs.',
    docs: 'paid',
    required: true,
  },
  {
    code: 'launch_token',
    where: 'check',
    status: 'a blocker at the check, 422 at the quote',
    cause: 'The request asks a project or hook launch for a token the launch would not deploy: a different supply, different decimals, fees, limits, pausing or minting.',
    fix:
      'Take the token terms out: every project or hook launch deploys 1,000,000,000 with 18 decimals, plain transfers, 10% to the swarm. Set `economics.poolBps` and `remainderTo` for how your 90% is split. For your own terms use `onchain: "custom_token"` with full `economics`.',
    observed: `${D}: a univ4_hook launch asking for 21,000,000 supply with 8 decimals, and a workflow asking for 1,000,000 supply, both returned launch_token with the full fixed-token text.`,
    docs: 'job-body',
    required: true,
  },
  {
    code: 'too_many_publishes',
    where: 'run',
    status: '429 on POST /sites/publish',
    cause: 'A seat published more than ten sites in a day through the device route. A paid job that hosts a site goes through the publisher service and does not hit this quota.',
    fix: 'Wait for `Retry-After`. If you are a requester, let the job host the site with `ipfs: true` or a site label instead of publishing from a seat.',
    observed: 'Not reproduced: it needs a paired device key.',
    docs: 'sites',
    required: true,
  },
  {
    code: 'no_panel',
    where: 'read',
    status: '404 on GET /jobs/:id/panel',
    cause: 'The job is not a research panel. Only `template: "research"` jobs have a panel; a research-report skill job has a result, not a panel.',
    fix: 'Read `GET /jobs/:id/result` for a report job, or `GET /oracle/requests/:id` for a question. Use `GET /research/panels` to list closed panels.',
    observed: `${D}: GET /jobs/96e5354f-6e81-4063-9fe2-6d1c44c7b192/panel (a create-image job) returned 404 {"error":"no_panel","detail":"that job has no panel"}.`,
    docs: 'research',
    required: true,
  },
  {
    code: 'unknown_schedule',
    where: 'check',
    status: 'a blocker at the check, 422 at the quote; 404 on GET /schedules/:id',
    cause: 'No schedule has that id. A schedule.topup names an id that was never created, or a typo.',
    fix: 'Copy the id from `GET /schedules?owner=0x…` or from the admission result of the schedule.create that made it.',
    observed: `${D}: schedule.topup with an all-zero UUID returned the blocker "no schedule has that id"; GET /schedules/<same id> returned 404 unknown_schedule.`,
    docs: 'schedules',
    required: true,
  },
  {
    code: 'invalid_owner',
    where: 'read',
    status: '400 on GET /schedules?owner=',
    cause: 'The `owner` query is not a 0x wallet address.',
    fix: 'Pass the full 0x address, 40 hex characters. Owners are stored lowercase; either case matches.',
    observed: `${D}: GET /schedules?owner=notawallet returned 400 {"error":"invalid_owner","detail":"owner must be a 0x wallet address"}.`,
    docs: 'schedules',
    required: true,
  },
  {
    code: 'evaluation_unavailable',
    where: 'check',
    status: 'transient; returned by a check or a quote when the evaluator cannot answer',
    cause: 'The judge that reads requests was unreachable or timed out. Nothing about your body caused it, and nothing was charged.',
    fix: 'Retry after a short wait with the same `requestKey`. If it persists, read `GET /health` for provider state.',
    observed: 'Not reproduced on the check date: every probe was judged. Listed from the assignment’s own notes.',
    docs: 'errors',
    required: true,
  },
  // Other codes a requester meets, observed or documented.
  {
    code: 'ambiguous_question',
    where: 'check',
    status: 'a blocker at the check, 422 at the quote',
    cause: 'The wording screen judged the oracle question to have more than one reasonable reading.',
    fix: 'Name the period, the unit, the rounding or the term you mean in the question itself; pin the rest under `definitions`. `allowAmbiguous: true` skips the screen and asks it as written.',
    observed: `${D}: "How many Transfer events did the IMD token (0xd34a…) emit on Ethereum mainnet in the window?" was refused; naming the event signature, the contract and "every from and to address included" passed.`,
    docs: 'oracle-body',
    required: false,
  },
  {
    code: 'invalid_cadence',
    where: 'check',
    status: 'a blocker at the check, 422 at the quote',
    cause: 'The schedule fires closer than the floor: ten minutes between questions, thirty between jobs.',
    fix: 'Use `PT10M` or longer for questions and `PT30M` or longer for jobs, or a cron that fires no closer.',
    observed: `${D}: {every: "PT5M"} on an oracle schedule returned "every must be at least 10m for this action".`,
    docs: 'schedule-body',
    required: false,
  },
  {
    code: 'unresolved_decision',
    where: 'check',
    status: 'a blocker at the check, 422 at the quote',
    cause: 'The workflow evaluator found a decision the request leaves open, such as whether source may be published separately from the site.',
    fix: 'Answer it in `context` ("GitHub publication approved") and keep `permissions` consistent with the draft flags.',
    observed: `${D}: returned alongside invalid_plan on the oversized workflow.`,
    docs: 'workflow-body',
    required: false,
  },
  {
    code: 'quote_expired',
    where: 'submit',
    status: '410',
    cause: 'The quote is older than 600 seconds.',
    fix: 'Quote again with a new `requestKey`.',
    observed: 'Documented from the docs.',
    docs: 'paid',
    required: false,
  },
  {
    code: 'invalid_quote_approval',
    where: 'submit',
    status: '400',
    cause: 'The EIP-712 QuoteApproval does not match: almost always the payment that was hashed into `paymentHash` differs, by one byte, from the one in the PAYMENT-SIGNATURE header.',
    fix: 'Hash the canonical JSON (sorted keys, no whitespace) of the exact object you encode into the header, after dropping `extensions`.',
    observed: 'Documented from the docs.',
    docs: 'quote-approval',
    required: false,
  },
  {
    code: 'payment_rejected',
    where: 'submit',
    status: '402',
    cause: 'The payment could not be settled; `reason` says why, for example `insufficient_funds` or a missing Permit2 allowance.',
    fix: 'Fund the wallet, approve Permit2 for IMD, and submit the same bytes again. Retries reuse the order and never charge twice.',
    observed: 'Documented from the docs.',
    docs: 'paid',
    required: false,
  },
  {
    code: 'origin_not_allowed',
    where: 'submit',
    status: '403',
    cause: 'A paid route was called from a cross-origin browser page.',
    fix: 'Call from a server or a command line. Public reads have CORS on selected routes; paid routes do not.',
    observed: 'Documented from the docs.',
    docs: 'base',
    required: false,
  },
  {
    code: 'request_limit',
    where: 'quote',
    status: '429',
    cause: 'More than 300 requests or 30 quotes a minute from one IP or one token. A check or an import counts as a quote.',
    fix: 'Wait for `Retry-After`. Batch your checks; a check per edit is fine, a check per keystroke is not.',
    observed: 'Documented from the docs.',
    docs: 'paid',
    required: false,
  },
  {
    code: 'too_many_reads',
    where: 'read',
    status: '429',
    cause: 'More than 120 public reads a minute from one IP on api.imd.fun.',
    fix: 'Read through the explorer (`https://explorer.imd.fun/api/...`) for more, or slow down.',
    observed: 'Documented from the docs.',
    docs: 'errors',
    required: false,
  },
];
